# ==========================================================
# Atajos de teclado para mpv y Anime4K (Escalado por GPU)
# ==========================================================

# Alternar pistas de audio y subtítulos
# (Presiona 'a' o '#' para cambiar idioma de audio, ej. Español Latino)
# (Presiona 'j' para cambiar pista de subtítulos)
a cycle audio
A cycle audio down

# ----------------------------------------------------------
# Atajos para activar/desactivar Anime4K (Reescalado IA)
# ----------------------------------------------------------
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode A (HQ - Máxima Calidad)"

CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A (Rápido)"

CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "Anime4K Desactivado (Original)"
